language: node_js
node_js: '10'
script: yarn generate

before_deploy: set -ev
  if [[ ${B_PHASE} = "firebase" ]]; then
    echo "> Firebase Deploy";
  fi

deploy:
  skip_cleanup: true
  provider: firebase
  env: D_PHASE=firebase
  token:
    secure: lmZNeJfbzdOOH15oCBs4KaxmPkjexzvyb/Uf6KdjgNjF1TR8ceKhtpjkGpI4kl3zdSGSS9JR9VaFmosnrLfX3bQPjH82GBZGNxgfTHyH1FOHaYxvCM2vN6qm0ACoXFI/hQJqZ67vMWeQWGkjPIc4YNrfi+eJ6l/LIaRwRuRXBKey5c3ukxPvrIbDjfZ5diDIPuaUWFRtkkmRnEwtE9vCyaLXSvJVQ0tYpAlel1yETWAwzlgjnqjdmta3fK4DrjxFYOPBBVm6BizgYcU/EjBcvYSBfFfXjCiEOKcmLInTmW8kaxrllIn+jjA0XOFMiDlqLVN1X2ltXYv4zGx04QZrd2xZ75CQND/mTDCNSJp7GaXpZw89p5T1s23bGNsiYHMWtmOshIlqgIHdQEYy9dhhWcoa5GWe9+mhZTxIw/8fw7nVWYyp9AkYJPLWFH9npQcFdkVkRitH1g7iW+g7n0n/nD807RlslbtOnGPJ2WpPa0XwSdzqh4Irietns8e3uZa3Cn+bJQFeUq/Y9iWssP2W9OSYrhqDkC88zh4dNhn2nlY800I5hrzupQE/bBhOLXLzZ+8jyCY+oFBXTWNTGK/pQnjs06Ryxr6oi20gahAx6uHx0BZrgPxCREoeq57vX4O2xqA1vzfsEDYp/By3ZbFIIDMiVm0qdlRHq68tHuChOc4=
