language: node_js
node_js: '10'
script: "yarn generate"
deploy:
  provider: firebase
  token:
    secure: bTaARWzBjNDfH2N1wpTMlwlXwiLFDXVrRAcCRN8ACqHmQ+FTJWj6HdRS+HiN97J2Q7PrYwHDlXbOPgRSSuZNj4lhgPrsfFXA5fuwYfQuNNXrOgHf/dNKRU1ddqPDeFylUiJRLQQd4jOfOqo9WICwmFRbHkunfOhcc3hY6ipmfps6qVnbU9YpQQiS8UZCWqHqQc1EczwFfbVnGtbOydvQ/O/ffIxaVNPzCrv2ARbY9xMMa6xsRdGqZ0+0QZDqDU0kRPP1JmCFMfSeNZyhYJkqEv0xp35F0KSvhyyXIAEWb1r1TGuFy5cmqYR+fl04oows/jGpPsCAQE7uqbZaZdHOMibZoOHrcmbR29VTndMR/lA8joMBPi1PteQRmNa7PXGH25JZ5E+hBuq8ry8lp1uIGRFXFKU5JVYbH7wzxP38TZCDU2pOE3CW2OdQrwUAPswF7h+o26YfqWrLawXDfhErZ89XwtKZFe9IFja/4UirUsmQh4X8riqbyCy5v0NaNldw6TS1ov5nvyolNpx8eziLFMUfeH/EMZ/zokRS5cn1khMcz4YvWToOeYofcKychjy0noOR0su+xqpHJsiTAQIl9eetX8gjnVqI+fWclyfsH+dNKKJ5LmUzuH3w2mVg43rfyIme+LfPlYxeR7D4J6x2c5XLlYP2wlie3xZDMSZhGZY=
